export function buildDigestEmail(digest) {
  if (!digest) return '';
  const items = digest.top10.map((story) => `<li><strong>${escapeHtml(story.headline)}</strong> — ${escapeHtml(story.sources?.[0]?.name || '')}</li>`).join('');
  const market = digest.marketRecap.map((story) => `<li>${escapeHtml(story.headline)}</li>`).join('');
  const policy = digest.policyRecap.map((story) => `<li>${escapeHtml(story.headline)}</li>`).join('');

  return `<!doctype html>
<html><head><meta charset="utf-8"><title>UnderCurrent Weekly Digest</title></head>
<body style="font-family:Arial, sans-serif; background:#f4f9ff; color:#10283f; padding:24px;">
  <h1 style="font-family:Georgia, serif;">Weekly Digest</h1>
  <p>${escapeHtml(digest.summary || '')}</p>
  <h2>Top 10</h2>
  <ol>${items}</ol>
  <h2>Market Recap</h2>
  <ul>${market || '<li>Market recap forthcoming.</li>'}</ul>
  <h2>Policy Recap</h2>
  <ul>${policy || '<li>Policy recap forthcoming.</li>'}</ul>
  <p style="margin-top:24px; font-size:12px; color:#506983;">Generated by The UnderCurrent.</p>
</body></html>`;
}

function escapeHtml(text) {
  return String(text || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}
